### ISSUE TITLE
Failure of build due to sharing between shared libs

### ISSUE THREAD

**Issue by st-clair-clarke** [srleecode/domain#112]
I have a libs/ng-shared/shared/domain and libs/ng-shared/shared-dx domains. directives in shared-dx depend on types in shared. Is this allowed?  Although compilation occur, the nx build always fail.

Is it possible to extract the TID into its own libs/ng-shared/ domain?

Below is a screenshot of the relationship

![image](https://github.com/srleecode/domain/assets/3227590/1dfba4a3-521b-4ec4-8db6-3a8ab35b8f7e)

**Comment by srleecode** [comment]
The shared-dx presentation can import types from shared/domain. However, in general you need to be careful not to have circular dependencies, i.e. A imports from B and B imports from A.

What is the build error you are getting.

**Comment by st-clair-clarke** [comment]
Errors:

'''
libs/ng-shared/shared-dx/domain/src/lib/dx-type-util.ts:19:21 - error TS6059: File '/home/stclair/workspace/nx/mf/med-soft/libs/ng-shared/shared/domain/src/index.ts' is not under 'rootDir' '/home/stclair/workspace/nx/mf/med-soft/libs/ng-shared/shared-dx/domain/src'. 'rootDir' is expected to contain all source files.
     The file is in the program because:
       Imported via '@medsoft/shared/domain' from file '/home/stclair/workspace/nx/mf/med-soft/libs/ng-shared/shared-dx/domain/src/lib/dx-type-util.ts'
       Imported via '@medsoft/shared/domain' from file '/home/stclair/workspace/nx/mf/med-soft/libs/ng-shared/shared-dx/domain/src/lib/dx-util.ts'
       Imported via '@medsoft/shared/domain' from file '/home/stclair/workspace/nx/mf/med-soft/libs/ng-shared/shared-dx/domain/src/lib/dx-validation-util.ts'
   
   19 import { TID } from '@medsoft/shared/domain'

'''

**Comment by st-clair-clarke** [comment]
'''
   libs/ng-shared/shared-dx/domain/src/lib/dx-type-util.ts:19:21 - error TS6059: File 'xom/nx/mf/med-soft/libs/ng-shared/shared/domain/src/index.ts' is not under 'rootDir' 'xom/nx/mf/med-soft/libs/ng-shared/shared-dx/domain/src'. 'rootDir' is expected to contain all source files.
     The file is in the program because:
       Imported via '@medsoft/shared/domain' from file 'xom/nx/mf/med-soft/libs/ng-shared/shared-dx/domain/src/lib/dx-type-util.ts'
       Imported via '@medsoft/shared/domain' from file 'xom/nx/mf/med-soft/libs/ng-shared/shared-dx/domain/src/lib/dx-util.ts'
       Imported via '@medsoft/shared/domain' from file 'xom/nx/mf/med-soft/libs/ng-shared/shared-dx/domain/src/lib/dx-validation-util.ts'
   
   19 import { TID } from '@medsoft/shared/domain'

;''

**Comment by srleecode** [comment]
This looks related to be related to your application. I would look at wherever you have defined rootDir and check if that is correct. Also, make sure when you import from different libraries that you use the tsconfig path. 

Are you able to reproduce the issue in the example repository in this branch:
- https://github.com/srleecode/domain-example/tree/112
