### ISSUE TITLE
Cannot import from a nested shared domain directory to another domain in the same scop

### ISSUE THREAD

**Issue by st-clair-clarke** [srleecode/domain#126]
I have the following hierarchy as shown in the screenshot.

![2024-01-06_09-49-cannot-import-from-domain-to-presentation](https://github.com/srleecode/domain/assets/3227590/1e8a0298-53a1-43b7-b670-596303910273)

I am trying to import the domain-layer TFrequency model into the presentation-layer frequency.component. However, the model is not being imported. The screenshot below shows that the Webstorm IDE sees the model....

![2024-01-06_09-56-ide-sees-model](https://github.com/srleecode/domain/assets/3227590/ccf347ba-27f6-4011-9acb-c406e7295207)

The IDE says it cannot build a module path to the model.

NB: I had corrected the duplicated errors I mentioned in my previous Issue by searching for the errors with case-sensitivity on and replaced the duplications. So I don't know if that did something.

Also, please take below at s snippet from my root eslintrc.json and see if there is somthing wrong with the scoping of scope:ng-clerk-shared.

![2024-01-06_10-03-eslintrc](https://github.com/srleecode/domain/assets/3227590/9b1ecadc-3a7d-4e67-9d86-4347228cb809)

The tree structure of libs/ng-clerk/** is shown below:

![2024-01-06_13-30-ng-shared](https://github.com/srleecode/domain/assets/3227590/62094c2e-63c7-4d88-8f3b-ffc983965eba)

The libs 'root-scope' share directory is shown below:

![2023-05-05_06-27](https://github.com/srleecode/domain/assets/3227590/fd66ca34-afb9-462b-b9c4-8fdd15424b66)

The intent of the libs/ng-clerk/share is to share its contents with libs/ng-history and libs/ng-examination ONLY.

Thanks

**Comment by srleecode** [comment]
I use vscode, so I haven't seen the error before which seems to be related to the Webstorm IDE. Can you check your tsconfig.base.json to see that there is the correct entry is there for the shared domain library and can you check that the file you want to import is exported in the index.ts of the shared domain library. After that, if you still get the error what happens when you manually add the import in the component file.

**Comment by st-clair-clarke** [comment]
Thanks. Maybe my packages got corrupted. I simple checkout from git and continue from there.
