### ISSUE TITLE
Errors attempting to run schema

### ISSUE THREAD

**Issue by st-clair-clarke** [srleecode/domain#22]
My attempt to generate srleecode schematic items always gives an errror

Executing task: ng generate @srleecode/domain:appGroupingFolder --name=xom --no-interactive --dry-run <

Cannot find module '@srleecode/domain/shared/utils'
Require stack:
- /home/stclair/__/@workspace/pim/node_modules/.pnpm/@srleecode+domain@12.7.2-alpha-1/node_modules/@srleecode/domain/generators/grouping-folder/create-app/src/lib/shared/initialise-workspace.js
- /home/stclair/__/@workspace/pim/node_modules/.pnpm/@srleecode+domain@12.7.2-alpha-1/node_modules/@srleecode/domain/generators/grouping-folder/create-app/src/generator.js
- /home/stclair/__/@workspace/pim/node_modules/.pnpm/@nrwl+tao@12.7.2/node_modules/@nrwl/tao/src/shared/workspace.js
- /home/stclair/__/@workspace/pim/node_modules/.pnpm/@nrwl+tao@12.7.2/node_modules/@nrwl/tao/src/commands/generate.js
- /home/stclair/__/@workspace/pim/node_modules/.pnpm/@nrwl+tao@12.7.2/node_modules/@nrwl/tao/index.js
- /home/stclair/__/@workspace/pim/node_modules/.pnpm/@nrwl+cli@12.7.2/node_modules/@nrwl/cli/lib/init-local.js
- /home/stclair/__/@workspace/pim/node_modules/.pnpm/@nrwl+cli@12.7.2/node_modules/@nrwl/cli/bin/nx.js
The terminal process "/usr/bin/bash '-l', '-c', '/home/stclair/__/@workspace/pim/node_modules/.bin/ng generate @srleecode/domain:appGroupingFolder --name=xom --no-interactive --dry-run', 'ng generate @srleecode/domain:appGroupingFolder --name=xom --no-interactive --dry-run'" failed to launch (exit code: 1).

Terminal will be reused by tasks, press any key to close it.

Any reason as to why this is occurring?

![image](https://user-images.githubusercontent.com/3227590/131254573-51007118-0af1-440c-9363-7a487e98eb68.png)

**Comment by srleecode** [comment]
Can you use 12.6.2?

I am going through a rewrite of the packages, so any of the published versions that end with alpha are not stable and are likely to have issues. I should be able to stabilize it soon.

**Comment by srleecode** [comment]
Closing as the latest alpha should not have this issue and 12.6.2 can be used until the code in alpha is ready to be released
