### ISSUE TITLE
Reducing circular references 

### ISSUE THREAD

**Issue by st-clair-clarke** [srleecode/domain#76]
I created a domain:appGroupingFolder and examined my eslintrc.json. The relevant snippet is shown below:

```
{
  "sourceTag": "domain:core",
  "onlyDependOnLibsWithTags": [
    "domain:core",
    "domain:shared"
  ],
  "notDependOnLibsWithTags": []
},
{
  "sourceTag": "domain:registrati
  "onlyDependOnLibsWithTags": [
    "domain:registration",
    "domain:shared"
  ],
  "notDependOnLibsWithTags": []
},
{
  "sourceTag": "type:shell",
  "onlyDependOnLibsWithTags": [
    "type:application",
    "type:directive",
    "type:domain",
    "type:feature",
    "type:shell",
    "type:ui",
    "type:util"
  ],
  "notDependOnLibsWithTags": []
},
{
  "sourceTag": "type:feature",
  "onlyDependOnLibsWithTags": [
    "type:application",
    "type:directive",
    "type:domain",
    "type:feature",
    "type:shell",
    "type:ui",
    "type:util"
  ],
  "notDependOnLibsWithTags": []
},
{
  "sourceTag": "type:ui",
  "onlyDependOnLibsWithTags": [
    "type:application",
    "type:directive",
    "type:domain",
    "type:feature",
    "type:shell",
    "type:ui",
    "type:util"
  ],
  "notDependOnLibsWithTags": []
},
{
  "sourceTag": "type:directive",
  "onlyDependOnLibsWithTags": [
    "type:application",
    "type:domain",
    "type:directive",
    "type:util"
  ],
  "notDependOnLibsWithTags": []
},
{
  "sourceTag": "type:application"
  "onlyDependOnLibsWithTags": [
    "type:application",
    "type:data-access",
    "type:domain",
    "type:util"
  ],
  "notDependOnLibsWithTags": []
},
{
  "sourceTag": "type:domain",
  "onlyDependOnLibsWithTags": [
    "type:domain"
  ],
  "notDependOnLibsWithTags": []
},
{
  "sourceTag": "type:data-access"
  "onlyDependOnLibsWithTags": [
    "type:data-access",
    "type:domain",
    "type:util"
  ],
  "notDependOnLibsWithTags": []
},
{
  "sourceTag": "type:util",
  "onlyDependOnLibsWithTags": [
    "type:domain",
    "type:util"
  ],
  "notDependOnLibsWithTags": []
}
            ]
          }
        ]
      }

```

1. Given that that the shell, feature and ui tags all have the same 'onlyDependsOnLibsWithTags' how will I prevent circular references between thise tags?
2. Is there a recommendation for the inheritance structure? For eg feature -> ui -> domain -> util?
3. Is it sufficient for me to remove the tags that I don't want from the  'onlyDependsOnLibsWithTags'? Or do I have to put the remove tag in the  'notDependsOnLibsWithTags'

**Comment by srleecode** [comment]
1. I am looking at changing it so that all components belong in one library called presentation.  This will remove any circular dependencies between shell, feature and ui.
2. The default eslint rules that get added are the recommended structure, e.g. util should only import things from other util and domain libraries.
3. It depends on your team and what you want to do. For me, onlyDependsOnLibsWithTags has been sufficient.

**Comment by st-clair-clarke** [comment]
Thanks for the reply. Consider the scenario where I have some functions that I use for field validation in a class entity. This function will be used globally in different libraries. I am thinking of placing the function in a shared domain. But domain should only depend on other domain. How can I get around this issue?

I like the proposed idea above regarding a single library presentation above. I developed several circular references that were difficult to correct. Any timeline for the update?

**Comment by srleecode** [comment]
I don't understand what the issue is. Different domain libraries can import from each other. For example, in the below the registration domain library could import from the shared one. 

registration (This is a grouping folder for the registration domain)
 - domain (This is the layer library for domain models etc. in the registration domain)
shared (This is a grouping folder for the shared domain)
 - domain (This is the layer library for domain models etc. in the shared domain)

Probably this week or next week

**Comment by st-clair-clarke** [comment]
Is this true?
>>The default eslint rules that get added are the recommended structure, **e.g. util should only import things from other util and domain libraries.**

Reading around the topic I saw where util shound HAVE NO DEPENDENCIES; WHILE DOMAIN CAN DEPEND ON OTHER DOMAIN OR UTIL.
[Moduliths in Angular with Nx](https://levelup.gitconnected.com/moduliths-in-angular-with-nx-b8b0076794fb)
![image](https://user-images.githubusercontent.com/3227590/224488513-fc72d24a-1c29-4b73-add8-a2f8355501f0.png)

**Comment by srleecode** [comment]
Each team might have different conventions that they want to enforce. The default lint rules are only setup once when you create the app grouping folder after that they can be changed by updating the eslint file. The above seems like an opinion to me and the convention they want to enforce. I couldn't see any utils libraries in their example app, so I don't know what it would look like for them in a real life larger application.

I think that in a real life larger application, people would want utils to be able to import things from other util libraries or a domain library. If you want to enforce that utils can depend on nothing else for your application, then you can update your eslint file for that.

**Comment by st-clair-clarke** [comment]
Thanks for the clarity - the different implementations have been a source of confusion for me.
