### ISSUE TITLE
Seems that path created by nx module federation is not recognised by srleecode/domain

### ISSUE THREAD

**Issue by st-clair-clarke** [srleecode/domain#97]
I created a nx module-federation app following the instructions ad [dynamic-module-federation-with-angular#creating-a-new-dynamic-host-applicationr](https://nx.dev/recipes/module-federation/dynamic-module-federation-with-angular#creating-a-new-dynamic-host-application). To create the application do the following at the command prompt:

```
  # Crate an empty workspace
  npx create-nx-workspace@latest --preset=empty --pm=pnpm
  pnpm add -D @nx/angular @nx/workspace
```

```
# create the module-federation dynamic host - replace
nx g @nx/angular:host medsoft --dynamic --standalone --standaloneConfig --no-interactive
```

```
# create the module-federation remote 
nx g @nx/angular:remote registration --host medsoft --standalone --standaloneConfig --no-interactive   
```

Run the application

```
nx serve medsoft
```

Now that the application works at http://localhost:4200/, install @srleecode/domain with 

```
pnpm add -D @srleecode/domain
```

Open the project withs Visual studio code and click on installed nx extension icon.
Click generate and select appGrouping foldder:

![image](https://github.com/srleecode/domain/assets/3227590/66d8faae-7c90-4030-9c0a-c182c20f87b2)

Note the error in the terminal
![image](https://github.com/srleecode/domain/assets/3227590/fe855844-45d2-46ec-a03b-5db587950617)

installed packages are shown below:

```
{
   "name": "@xom/source",
   "version": "0.0.0",
   "license": "MIT",
   "scripts": {},
   "private": true,
   "dependencies": {
      "@angular/animations": "~16.0.0",
      "@angular/common": "~16.0.0",
      "@angular/compiler": "~16.0.0",
      "@angular/core": "~16.0.0",
      "@angular/forms": "~16.0.0",
      "@angular/platform-browser": "~16.0.0",
      "@angular/platform-browser-dynamic": "~16.0.0",
      "@angular/router": "~16.0.0",
      "rxjs": "~7.8.0",
      "tslib": "^2.3.0",
      "zone.js": "~0.13.0"
   },
   "devDependencies": {
      "@angular-architects/ddd": "^3.1.1",
      "@angular-devkit/build-angular": "~16.0.0",
      "@angular-devkit/core": "~16.0.0",
      "@angular-devkit/schematics": "~16.0.0",
      "@angular-eslint/eslint-plugin": "~16.0.0",
      "@angular-eslint/eslint-plugin-template": "~16.0.0",
      "@angular-eslint/template-parser": "~16.0.0",
      "@angular/cli": "~16.0.0",
      "@angular/compiler-cli": "~16.0.0",
      "@angular/language-service": "~16.0.0",
      "@nx/cypress": "16.2.1",
      "@nx/eslint-plugin": "16.2.1",
      "@nx/jest": "16.2.1",
      "@nx/js": "16.2.1",
      "@nx/linter": "16.2.1",
      "@nx/web": "16.2.1",
      "@nx/workspace": "16.2.1",
      "@schematics/angular": "~16.0.0",
      "@srleecode/domain": "^13.10.18",
      "@types/jest": "^29.4.0",
      "@types/node": "16.11.7",
      "@typescript-eslint/eslint-plugin": "^5.58.0",
      "@typescript-eslint/parser": "^5.58.0",
      "cypress": "^12.11.0",
      "eslint": "~8.15.0",
      "eslint-config-prettier": "8.1.0",
      "eslint-plugin-cypress": "^2.10.3",
      "jest": "^29.4.1",
      "jest-environment-jsdom": "^29.4.1",
      "jest-preset-angular": "~13.1.0",
      "nx": "16.2.1",
      "nx-cloud": "latest",
      "prettier": "^2.6.2",
      "ts-jest": "^29.1.0",
      "ts-node": "10.9.1",
      "typescript": "~5.0.2"
   }
}

```

Thanks for helping

**Comment by srleecode** [comment]
Can you update "@srleecode/domain" to a 16 version and try it again

**Comment by st-clair-clarke** [comment]
The terminal error message has changed as shown below, but still does not execute as expected:

![image](https://github.com/srleecode/domain/assets/3227590/d1ae523f-a6c6-48c2-99f1-dba5878c2ebd)
![image](https://github.com/srleecode/domain/assets/3227590/f7b7cf0c-f06c-468e-a0b2-0fc59e125b73)

**Comment by srleecode** [comment]
I updated to 16.2.2. Using that I tried the above steps and was able to run the generator with any errors. Can you try it with 16.2.2. If you still get the error, can you create a repository with an example that gets  the error you are seeing.

**Comment by st-clair-clarke** [comment]
Working!! (16.2.2) Thank you.

**Comment by st-clair-clarke** [comment]
Using verstion 16.2.2

Spoke a little to soon. The following are working fine: Generation of 
1. grouping folders
2. application
3. domain
4. util


The following are not working: Generation of:
1. component
2. directive
3. infrastructure
4. presentation-layer

The ones that are not working have a similar error in the terminal as shown below:

![image](https://github.com/srleecode/domain/assets/3227590/50acd6d7-2457-40a1-a6bd-1da8bc01578c)

I saw the same error in the initial issue - maybe a little tweaking in the ones not working similar to what was done before.

Thanks.

**Comment by srleecode** [comment]
Does the grouping folder you are using exist? For example, locally this works `npx nx generate @srleecode/domain:ngDirective --groupingFolder=libs\ng-medsoft\test --name=test --no-interactive --dry-run`  and this fails with the error you are seeing `npx nx generate @srleecode/domain:ngDirective --groupingFolder=ng-medsoft\test --name=test --no-interactive --dry-run `.

**Comment by st-clair-clarke** [comment]
You were correct! It is now working.
